/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/turnos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los registros */
        get: operations["getAll"];
        put?: never;
        /** Crear un nuevo turno */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnos/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear múltiples turnos */
        post: operations["createMultiple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los registros */
        get: operations["getAll_1"];
        put?: never;
        /** Crear un nuevo servicio */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear múltiples servicios */
        post: operations["createMultiple_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los registros */
        get: operations["getAll_2"];
        put?: never;
        /** Crear un nuevo cliente */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear múltiples clientes */
        post: operations["createMultiple_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/administradores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener todos los registros */
        get: operations["getAll_3"];
        put?: never;
        /** Crear un nuevo administrador */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/administradores/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Autentica un administrador por email y contraseña, devuelve JWT
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/administradores/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear múltiples administradores */
        post: operations["createMultiple_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un registro por ID */
        get: operations["getById"];
        put?: never;
        post?: never;
        /** Eliminar un registro por ID */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Actualizar parcialmente un registro por ID */
        patch: operations["update"];
        trace?: never;
    };
    "/servicios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un registro por ID */
        get: operations["getById_1"];
        put?: never;
        post?: never;
        /** Eliminar un registro por ID */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /** Actualizar parcialmente un registro por ID */
        patch: operations["update_1"];
        trace?: never;
    };
    "/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un registro por ID */
        get: operations["getById_2"];
        put?: never;
        post?: never;
        /** Eliminar un registro por ID */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        /** Actualizar parcialmente un registro por ID */
        patch: operations["update_2"];
        trace?: never;
    };
    "/administradores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un registro por ID */
        get: operations["getById_3"];
        put?: never;
        post?: never;
        /** Eliminar un registro por ID */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        /** Actualizar parcialmente un registro por ID */
        patch: operations["update_3"];
        trace?: never;
    };
    "/turnos/{page}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener registros paginados */
        get: operations["getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnos/findDateTimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener fechas y horas ocupadas
         * @description Devuelve una lista con las fechas y horas que ya tienen turno asignado
         */
        get: operations["getFechasOcupadas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/turnos/exists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar si un registro existe por ID */
        get: operations["existsById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios/{page}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener registros paginados */
        get: operations["getPage_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servicios/exists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar si un registro existe por ID */
        get: operations["existsById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificar estado del backend
         * @description Devuelve un mensaje de confirmación si el servidor está funcionando
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estadisticas/panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener panel de estadísticas
         * @description Devuelve turnos hoy, ayer, ingresos del mes, servicios más pedidos y horarios con más actividad
         */
        get: operations["estadisticas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{page}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener registros paginados */
        get: operations["getPage_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/exists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar si un registro existe por ID */
        get: operations["existsById_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/administradores/{page}/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener registros paginados */
        get: operations["getPage_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/administradores/exists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificar si un registro existe por ID */
        get: operations["existsById_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Datos para crear un nuevo turno (incluye datos del cliente) */
        TurnoRequestDTO: {
            /**
             * Format: date-time
             * @description Fecha y hora del turno
             */
            fechaHora: string;
            /**
             * Format: int64
             * @description ID del servicio solicitado
             * @example 1
             */
            idServicio: number;
            /**
             * @description Teléfono del cliente (si no existe, se crea)
             * @example 1155551234
             */
            telefonoCliente: string;
            /**
             * @description Nombre del cliente
             * @example Juan
             */
            nombreCliente: string;
            /**
             * @description Apellido del cliente
             * @example Pérez
             */
            apellidoCliente: string;
            /**
             * @description Email del cliente (opcional)
             * @example juan.perez@email.com
             */
            emailCliente?: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: Record<string, never>;
            };
        };
        /** @description Turno registrado con datos del cliente y servicio */
        TurnoResponseDTO: {
            /**
             * Format: int64
             * @description ID único del turno
             * @example 1
             */
            id: number;
            /**
             * Format: date-time
             * @description Fecha y hora del turno
             */
            fechaHora: string;
            /**
             * @description Teléfono del cliente
             * @example 1155551234
             */
            telefonoCliente: string;
            /**
             * @description Nombre del cliente
             * @example Juan
             */
            nombreCliente: string;
            /**
             * @description Apellido del cliente
             * @example Pérez
             */
            apellidoCliente: string;
            /**
             * @description Email del cliente
             * @example juan.perez@email.com
             */
            emailCliente?: string;
            /**
             * Format: int64
             * @description ID del servicio reservado
             * @example 1
             */
            idServicio: number;
            /**
             * @description Nombre del servicio
             * @example Corte de pelo
             */
            tipoServicio: string;
            /**
             * Format: float
             * @description Precio del servicio
             * @example 1500
             */
            precioServicio: number;
        };
        /** @description Datos para crear o actualizar un servicio */
        ServicioRequestDTO: {
            /**
             * @description Nombre o tipo de servicio ofrecido
             * @example Corte de pelo
             */
            tipo: string;
            /**
             * Format: float
             * @description Precio del servicio en pesos
             * @example 1500
             */
            precio?: number;
        };
        /** @description Servicio disponible en la barbería */
        ServicioResponseDTO: {
            /**
             * Format: int64
             * @description ID único del servicio
             * @example 1
             */
            id: number;
            /**
             * @description Nombre o tipo de servicio
             * @example Corte de pelo
             */
            tipo: string;
            /**
             * Format: float
             * @description Precio del servicio en pesos
             * @example 1500
             */
            precio: number;
        };
        /** @description Datos para crear o actualizar un cliente */
        ClienteRequestDTO: {
            /**
             * @description Número de teléfono del cliente (usado como ID)
             * @example 1155551234
             */
            telefono: string;
            /**
             * @description Nombre del cliente
             * @example Juan
             */
            nombre: string;
            /**
             * @description Apellido del cliente
             * @example Pérez
             */
            apellido: string;
            /**
             * @description Email del cliente
             * @example juan.perez@email.com
             */
            email?: string;
        };
        /** @description Cliente registrado en la barbería */
        ClienteResponseDTO: {
            /**
             * @description Número de teléfono del cliente
             * @example 1155551234
             */
            telefono: string;
            /**
             * @description Nombre del cliente
             * @example Juan
             */
            nombre: string;
            /**
             * @description Apellido del cliente
             * @example Pérez
             */
            apellido: string;
            /**
             * @description Email del cliente
             * @example juan.perez@email.com
             */
            email?: string;
        };
        /** @description Datos para crear un nuevo administrador */
        AdministradorRequestDTO: {
            /**
             * @description Nombre del administrador
             * @example Carlos
             */
            nombre: string;
            /**
             * @description Apellido del administrador
             * @example López
             */
            apellido: string;
            /**
             * @description Email del administrador (usado para iniciar sesión)
             * @example carlos.lopez@barberia.com
             */
            email: string;
            /**
             * @description Contraseña en texto plano (se hashea antes de persistir)
             * @example miPassword123
             */
            contrasenia: string;
        };
        /** @description Administrador registrado en el sistema */
        AdministradorResponseDTO: {
            /**
             * Format: int64
             * @description ID único del administrador
             * @example 1
             */
            id: number;
            /**
             * @description Nombre del administrador
             * @example Carlos
             */
            nombre: string;
            /**
             * @description Apellido del administrador
             * @example López
             */
            apellido: string;
            /**
             * @description Email del administrador
             * @example carlos.lopez@barberia.com
             */
            email: string;
        };
        /** @description Credenciales de inicio de sesión para administradores */
        LoginRequestDTO: {
            /**
             * @description Email del administrador
             * @example admin@barberia.com
             */
            email: string;
            /**
             * @description Contraseña del administrador
             * @example miPassword123
             */
            contrasenia: string;
        };
        /** @description Respuesta de inicio de sesión con JWT */
        LoginResponseDTO: {
            /**
             * Format: int64
             * @description ID único del administrador
             * @example 1
             */
            id?: number;
            /**
             * @description Nombre del administrador
             * @example Carlos
             */
            nombre?: string;
            /**
             * @description Apellido del administrador
             * @example López
             */
            apellido?: string;
            /**
             * @description Email del administrador
             * @example carlos@barberia.com
             */
            email?: string;
            /**
             * @description Token JWT para autenticación
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token?: string;
        };
        Cliente: {
            nombre?: string;
            apellido?: string;
            email?: string;
            telefono?: string;
        };
        Servicio: {
            /** Format: int64 */
            id?: number;
            tipo?: string;
            /** Format: float */
            precio?: number;
        };
        Turno: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            fechaHora?: string;
            cliente?: components["schemas"]["Cliente"];
            servicio?: components["schemas"]["Servicio"];
        };
        Administrador: {
            nombre?: string;
            apellido?: string;
            email?: string;
            /** Format: int64 */
            id?: number;
            contrasenia?: string;
        };
        PageTurno: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["Turno"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        PageServicio: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["Servicio"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        /** @description Cantidad de turnos realizados en una hora específica */
        HorarioEstadisticaDTO: {
            /**
             * Format: int32
             * @description Hora del día (0-23)
             * @example 14
             */
            hora?: number;
            /**
             * Format: int64
             * @description Cantidad de turnos realizados en esa hora
             */
            cantidadRealizado?: number;
        };
        /** @description Ingreso total registrado en un día específico */
        IngresoDiarioDTO: {
            /**
             * Format: date-time
             * @description Fecha del ingreso
             */
            fecha?: string;
            /**
             * Format: double
             * @description Monto total ingresado en el día
             */
            ingresoTotal?: number;
        };
        /** @description Panel completo de estadísticas del negocio */
        PanelEstadisticaDTO: {
            /**
             * Format: int32
             * @description Cantidad de turnos para el día de hoy
             */
            turnosHoy?: number;
            /**
             * Format: int32
             * @description Cantidad de turnos para el día de ayer
             */
            turnosAyer?: number;
            /**
             * Format: double
             * @description Ingresos totales del mes actual
             */
            ingresosMes?: number;
            /**
             * Format: double
             * @description Ingresos totales del mes anterior
             */
            ingresosMesAnterior?: number;
            /**
             * Format: int64
             * @description Cantidad total de clientes registrados
             */
            cantClientes?: number;
            /** @description Ingresos diarios de los últimos 30 días */
            ingresosDiarios?: components["schemas"]["IngresoDiarioDTO"][];
            /** @description Servicios más realizados en el último mes */
            servicios?: components["schemas"]["ServicioEstadisticaDTO"][];
            /** @description Horarios con más turnos en lo que va del año */
            horarios?: components["schemas"]["HorarioEstadisticaDTO"][];
        };
        /** @description Estadística de un servicio: cantidad de veces realizado en un período */
        ServicioEstadisticaDTO: {
            /**
             * Format: int64
             * @description ID del servicio
             */
            id?: number;
            /** @description Nombre o tipo del servicio */
            nombre?: string;
            /**
             * Format: int64
             * @description Cantidad de veces que se realizó el servicio
             */
            cantidadRealizado?: number;
        };
        PageCliente: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["Cliente"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageAdministrador: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["Administrador"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnoResponseDTO"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnoRequestDTO"];
            };
        };
        responses: {
            /** @description Turno creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnoResponseDTO"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Servicio no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createMultiple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnoRequestDTO"][];
            };
        };
        responses: {
            /** @description Turnos creados */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnoResponseDTO"][];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Servicio no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServicioResponseDTO"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicioRequestDTO"];
            };
        };
        responses: {
            /** @description Servicio creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServicioResponseDTO"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createMultiple_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicioRequestDTO"][];
            };
        };
        responses: {
            /** @description Servicios creados */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServicioResponseDTO"][];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteRequestDTO"];
            };
        };
        responses: {
            /** @description Cliente creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ya existe un cliente con ese teléfono */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createMultiple_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteRequestDTO"][];
            };
        };
        responses: {
            /** @description Clientes creados */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"][];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ya existe un cliente con ese teléfono */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getAll_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdministradorResponseDTO"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdministradorRequestDTO"];
            };
        };
        responses: {
            /** @description Administrador creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdministradorResponseDTO"];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ya existe un administrador con ese email */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDTO"];
            };
        };
        responses: {
            /** @description Inicio de sesión exitoso */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponseDTO"];
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createMultiple_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdministradorRequestDTO"][];
            };
        };
        responses: {
            /** @description Administradores creados */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdministradorResponseDTO"][];
                };
            };
            /** @description Datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ya existe un administrador con ese email */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnoResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Turno"];
            };
        };
        responses: {
            /** @description Registro actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnoResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServicioResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servicio"];
            };
        };
        responses: {
            /** @description Registro actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServicioResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cliente"];
            };
        };
        responses: {
            /** @description Registro actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdministradorResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registro eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Administrador"];
            };
        };
        responses: {
            /** @description Registro actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdministradorResponseDTO"];
                };
            };
            /** @description Registro no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                size: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageTurno"];
                };
            };
        };
    };
    getFechasOcupadas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de fechas y horas ocupadas en formato ISO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    existsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description true si existe, false si no */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getPage_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                size: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageServicio"];
                };
            };
        };
    };
    existsById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description true si existe, false si no */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mensaje de confirmación del servidor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    estadisticas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Panel de estadísticas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PanelEstadisticaDTO"];
                };
            };
            /** @description Error interno al generar estadísticas */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getPage_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                size: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCliente"];
                };
            };
        };
    };
    existsById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description true si existe, false si no */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getPage_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                size: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de registros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdministrador"];
                };
            };
        };
    };
    existsById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description true si existe, false si no */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
}
